
# Site settings
title: Lu laboratory @ Peking University
lab_name: Lu Laboratory
email: tianlu@bjmu.edu.cn
institution: Peking University
description: Lu Lab for cutting-edge technologies for spatiotemporal multiomics
baseurl: ""
url: "http://lulabpku.github.io"
github_username:  lulabpku
images_dir: "/images/"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
include: ["_pages"]
permalink: /:title/

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
  
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
