# Site settings
title: Lu laboratory @ Peking University
lab_name: Lu Laboratory
email: tianlu@bjmu.edu.cn
institution: Peking University
description: >
The Lu Lab for cutting-edge technologies for spatiotemporal multiomics
baseurl: ""
url: "http://lulabpku.github.io"
github_username:  lulabpku
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
